produtos:
    pattern:  /
    defaults: { _controller: "AndaimeBackendBundle:Product:index" }

produtos_show:
    pattern:  /{id}/show
    defaults: { _controller: "AndaimeBackendBundle:Product:show" }

produtos_new:
    pattern:  /new
    defaults: { _controller: "AndaimeBackendBundle:Product:new" }

produtos_create:
    pattern:  /create
    defaults: { _controller: "AndaimeBackendBundle:Product:create" }
    requirements: { _method: post }

produtos_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AndaimeBackendBundle:Product:edit" }

produtos_update:
    pattern:  /{id}/update
    defaults: { _controller: "AndaimeBackendBundle:Product:update" }
    requirements: { _method: post|put }

produtos_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AndaimeBackendBundle:Product:delete" }
    requirements: { _method: post|delete }
