AndaimeBackendBundle_produtos:
        resource: "@AndaimeBackendBundle/Resources/config/routing/product.yml"
        prefix:   /produtos

AndaimeBackendBundle_fotos:
        resource: "@AndaimeBackendBundle/Resources/config/routing/picture.yml"
        prefix:   /fotos