parameters:
#    andaime_backend.example.class: Andaime\BackendBundle\Example

services:
#    andaime_backend.example:
#        class: %andaime_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
