andaime_frontend_homepage:
    pattern:  /
    defaults: { _controller: AndaimeFrontendBundle:Default:index }

andaime_frontend_product:
    pattern:  /produtos
    defaults: { _controller: AndaimeFrontendBundle:Default:product }

andaime_frontend_contact:
    pattern:  /contato
    defaults: { _controller: AndaimeFrontendBundle:Default:contact }

andaime_frontend_about:
    pattern:  /sobre
    defaults: { _controller: AndaimeFrontendBundle:Default:about }

andaime_frontend_service:
    pattern:  /servicos
    defaults: { _controller: AndaimeFrontendBundle:Default:service }