andaime_frontend_homepage:
    pattern:  /
    defaults: { _controller: AndaimeFrontendBundle:Default:index }

andaime_frontend_product:
    pattern:  /produtos
    defaults: { _controller: AndaimeFrontendBundle:Default:product }

andaime_frontend_view_product:
    pattern:  /produto/{product}
    defaults: { _controller: AndaimeFrontendBundle:Default:viewProduct }

andaime_frontend_contact:
    pattern:  /contato
    defaults: { _controller: AndaimeFrontendBundle:Default:contact }

andaime_frontend_about:
    pattern:  /empresa
    defaults: { _controller: AndaimeFrontendBundle:Default:about }

andaime_frontend_manual:
    pattern:  /manuais
    defaults: { _controller: AndaimeFrontendBundle:Default:manual }

andaime_frontend_view_manual:
    pattern:  /manual/{manual}
    defaults: { _controller: AndaimeFrontendBundle:Default:viewManual }

andaime_frontend_map:
    pattern:  /mapa
    defaults: { _controller: AndaimeFrontendBundle:Default:map }