parameters:
#    andaime_frontend.example.class: Andaime\FrontendBundle\Example

services:
#    andaime_frontend.example:
#        class: %andaime_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
