security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: 123, roles: [ 'ROLE_USER' ] }
                    admin: { password: 123, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        admin_secured_area:
            pattern: /admin/.*
            #provider: entity_admin
            provider: in_memory
            anonymous: ~
            form_login:
                check_path: login_check
                login_path: admin_login
                #csrf_provider: form.csrf_provider
            logout:
                path:   /admin/logout
                target: /

    #firewalls:
    #    dev:
    #        pattern:  ^/(_(profiler|wdt)|css|images|js)/
    #        security: false

    #    login:
    #        pattern:  ^/admin/login$
    #        security: false

    #   secured_area:
    #        pattern:    ^/admin/
    #        form_login:
    #            check_path: _security_check
    #            login_path: admin_login
    #        logout:
    #            path:   admin_logout
    #            target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        admin_login:
            path: /admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        #admin_area:
        #    path: /admin/.*
        #    roles: ROLE_ADMIN
